### ISSUE TITLE
Sidebar admin

### ISSUE THREAD

**Issue by andy200486** [magix-cms/magixcms#71]
Pourquoi est-ce que tu n'as pas fait le même système pour la page d'accueil avec les langues ?
Mettre aussi les couleurs comme sur le dashboard : 

``` css
.label, .badge {
background-color: #3A87AD;
}

.label:hover, .badge:hover {
background-color: #000000;
}
```
